pipeline {
    environment {
        CC_LIST = 'pablo@hoodoo.digital'
        PIPE_NAME = 'Crawler'
    }

    agent { docker { image 'python:3.7.2' } }

    stages {
        stage('crawler') {
            steps {
                sh """
                    python3 -m venv env
                    . ./env/bin/activate 
                    pip3 install -r requirements.txt
                    mkdir -p results
                    scrapy runspider scripts/crawl.py
                """
            }
            post {
                always {
                    archiveArtifacts artifacts: 'results/*.csv', fingerprint: true
                }
            }
        }
   }
   post {
        always {

             mail to: "${CC_LIST}",
             from: 'pablo@hoodoo.digital',
             subject: "Process completed ${PIPE_NAME}: ${currentBuild.fullDisplayName} [${env.BUILD_NUMBER}]",
             body: """ CRAWL REPORT

                 Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]':

                 Job Name: ${env.JOB_NAME}
                 Job Number: ${env.BUILD_NUMBER}
                 Check crawlr report at  ${env.BUILD_URL}results/
                 """
        }
    }
}